version: '3'
services:
  web:
    container_name: web 
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
  
  app:
    container_name: app
    build: ./app
    env_file: ./config/.env
    environment:
      DATABASE_HOST: db
    depends_on: 
      - db 
    volumes: 
      - ./www/html:/var/www/html
      - ./app/log/xdebug.log:/tmp/log/xdebug.log
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    container_name: db
    image: mysql:5.7.19
    env_file: ./config/.env
    ports:
      - "3306:3306"
    volumes: 
      - db-data:/var/lib/mysql
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initialsql

volumes: 
  db-data: